apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: {name}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: openebs-lvmpv
---
apiVersion: v1
kind: Pod
metadata:
  name: {name}
spec:
  containers:
    - name: my-container
      image: busybox:latest
      volumeMounts:
        - name: shared-volume
          mountPath: /data
            #readOnly: true
      command:
      - /bin/sh
      - -c
      - while true; do echo hello world; sleep 1; done
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 10m
          memory: 20Mi
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: {name}
