apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      securityContext:
        runAsUser: 0
          #privileged: true
      volumes:
      - name: dev
        # hostPath:
        #   path: /dev
        persistentVolumeClaim:
          claimName: pvc-test
      containers:
      - name: ubuntu
        securityContext:
          privileged: true
        command:
        - /bin/bash
        - -c
        - while true; do echo hello world; sleep 1; done
        image: ubuntu:latest
        ports:
        - containerPort: 80
        # volumeDevices:
        # - name: dev
        #   devicePath: /dev/lvmvg
        volumeMounts:
        - name: dev
          mountPath: /dev
