apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: my-container
      image: ubuntu:latest
      volumeMounts:
        - name: shared-volume
          mountPath: /data
          readOnly: true
      command:
      - /bin/bash
      - -c
      - while true; do echo hello world; sleep 1; done
      securityContext:
        privileged: true
  volumes:
    - name: shared-volume
      hostPath:
        path: /dev
      # persistentVolumeClaim:
      #   claimName: ubuntu-ubuntu-0
