apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # annotations:
  #   # path: /root
  #   pv.kubernetes.io/bind-completed: "yes"
  #   pv.kubernetes.io/bound-by-controller: "yes"
  #   # value: "1"
  #   volume.beta.kubernetes.io/storage-provisioner: local.csi.openebs.io
  #   volume.kubernetes.io/selected-node: k8s
  #   volume.kubernetes.io/storage-provisioner: local.csi.openebs.io
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-test
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-lvmpv
  # volumeMode: Filesystem
  # volumeName: pvc-38eecef3-5ce0-4000-917a-024ed5105683-bak

