apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: shared-volume
          mountPath: /data
          readOnly: true
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: ubuntu-ubuntu-0
