apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: local.csi.openebs.io
  creationTimestamp: "2023-08-25T04:14:42Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-38eecef3-5ce0-4000-917a-024ed5105683-bak
  resourceVersion: "7372201"
  uid: 87ecbe39-6c7b-485a-8fda-fd760d2a0d21
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ubuntu-ubuntu-0
    namespace: default
    resourceVersion: "7372183"
    uid: 38eecef3-5ce0-4000-917a-024ed5105683
  csi:
    driver: local.csi.openebs.io
    fsType: ext4
    volumeAttributes:
      openebs.io/cas-type: localpv-lvm
      openebs.io/volgroup: lvmvg
      storage.kubernetes.io/csiProvisionerIdentity: 1692887823086-8081-local.csi.openebs.io
    volumeHandle: pvc-38eecef3-5ce0-4000-917a-024ed5105683-bak
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: openebs.io/nodename
          operator: In
          values:
          - k8s
  persistentVolumeReclaimPolicy: Delete
  storageClassName: openebs-lvmpv
  volumeMode: Filesystem
status:
  phase: Bound
