apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: shared-volume
          mountPath: /data
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: my-pvc

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: shared-volume
          mountPath: /data
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: my-pvc
