apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ubuntu
  name: ubuntu
spec:
  minReadySeconds: 10
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ubuntu
  serviceName: ubuntu
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubuntu
        restartTime: "20230817111253"
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - while true; do echo hello world; sleep 1; done
        image: ubuntu:latest
        imagePullPolicy: Always
        name: ubuntu
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 51Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root
          name: ubuntu
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: ubuntu
      annotations:
        path: /root
        value: "1"
      creationTimestamp: null
      name: ubuntu
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
