apiVersion: v1
kind: Namespace
metadata:
  name: backup-system
--- 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pvc-backup
  # labels:
  #   app: controller
  namespace: backup-system
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /root/manager
        env:
        - name: AWS_ACCESS_KEY_ID
          value: test
        - name: AWS_SECRET_ACCESS_KEY
          value: testtest
        - name: SRC
          value: /dev/lvmvg
        - name: TMP
          value: /tmp
        - name: RESTIC_REPOSITORY
          value: s3:http://10.162.17.233:9000/test
        - name: RESTIC_PASSWORD
          value: test
        image: sakcer/restic-server:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          privileged: true
        # terminationMessagePath: /dev/termination-log
        # terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      securityContext:
        runAsUser: 0
      serviceAccount: pvc-backup
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pods/
        name: data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-backup
  namespace: backup-system
